apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - adservice/app.yaml
  - authservice/app.yaml
  - cartservice/app.yaml
  - checkoutservice/app.yaml
  - currencyservice/app.yaml
  - emailservice/app.yaml
  - frontend/app.yaml
  - loadgenerator/app.yaml
  - paymentservice/app.yaml
  - productcatalogservice/app.yaml
  - recommendationservice/app.yaml
  - shippingservice/app.yaml
  - shoppingassistantservice/app.yaml
