apiVersion: v1
kind: Service
metadata:
  name: shoppingassistantservice
  labels:
    app: shoppingassistantservice
spec:
  type: ClusterIP
  selector:
    app: shoppingassistantservice
  ports:
  - name: http
    port: 80
    targetPort: 8080
