apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - adservice/deployment.yaml
  - adservice/service.yaml
  - cartservice/deployment.yaml
  - cartservice/service.yaml
  - checkoutservice/deployment.yaml
  - checkoutservice/service.yaml
  - currencyservice/deployment.yaml
  - currencyservice/service.yaml
  - emailservice/deployment.yaml
  - emailservice/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - loadgenerator/deployment.yaml
  - paymentservice/deployment.yaml
  - paymentservice/service.yaml
  - productcatalogservice/deployment.yaml
  - productcatalogservice/service.yaml
  - recommendationservice/deployment.yaml
  - recommendationservice/service.yaml
  - shippingservice/deployment.yaml
  - shippingservice/service.yaml
  - shoppingassistantservice/deployment.yaml
  - shoppingassistantservice/service.yaml
